FORMAT: 1A
HOST: http://stage.api.ingresso.art.br/api/v1/

# Ingresso.Art

Documentação da API Ingresso.Art

# Data Structures

## Blog Post (object)
+ id: 42 (number, required)
+ text: Hello Worldeeee (string)
+ author (Author) - Author of the blog post.

## Author (object)
+ name: Luciana Lima - Nome do cara
+ email: loo@intergalactic.com

## User (object)
+ id
+ nome
+ email
+ password
+ remember_token
+ tipo_documento
+ documento
+ telefone
+ banco
+ agencia
+ conta
+ api_key
+ ativo
+ admin
+ produtor
+ data_nascimento


## Evento (object)
+ id (number)
+ nome (string)
+ descricao (string)
+ data (string)
+ hora (string)
+ local (string)
+ genero (string)
+ cidade (string)
+ estado (string)
+ ativo (boolean)
+ deleted_at
+ created_at
+ updated_at
+ user_id (string)
+ gratuito (string)
+ privado (string)
+ identificador (string)

# Grupo Eventos

## Eventos [/evento]

### Lista todos os eventos [GET]

+ Response 200 (application/json)
    + Attributes (Evento)

### Recupera um Evento [GET]

+ Response 200 (application/json)
    + Attributes (Evento)