FORMAT: 1A
HOST: http://stage.api.ingresso.art.br/api/v1/

# Ingresso.Art

Documentação da API Ingresso.Art

# Data Structures

## User (object)
+ id
+ nome
+ email
+ password
+ remember_token
+ tipo_documento
+ documento
+ telefone
+ banco
+ agencia
+ conta
+ api_key
+ ativo
+ admin
+ produtor
+ data_nascimento

## Evento (object)
+ id (number)
+ nome (string)
+ descricao (string)
+ data (string)
+ hora (string)
+ local (string)
+ genero (string)
+ cidade (string)
+ estado (string)
+ ativo (boolean)
+ deleted_at
+ created_at
+ updated_at
+ user_id (string)
+ gratuito (string)
+ privado (string)
+ identificador (string)

# Group Website

## Básicas [/]

### Lista todos os eventos [GET /evento]
+ Response 200 (application/json)
    + Attributes (array[Evento])

### Lista um evento [GET /evento/{id}]
+ Parameters
    + id (string)

+ Response 200 (application/json)
    + Attributes (Evento)

## Cria um usuário [POST /create]

+ Request (application/json)

        {
            "nome":"Luciana Lima",
            "email": "luciana@ingresso.art.br",
            "password":"123123",
            "tipo_documento":"CPF",
            "documento":"06212660948",
            "telefone":"96004955",
            "data_nascimento":"04/04/1988"
        }
        
+ Response 200 (application/json)
    + Attributes (User)

## Ativa usuário [POST /ativar/{token}]

+ Parameters
    + token (string)

+ Response 200 (application/json)

## Login [POST /login]

+ Response 200 (application/json)


## Usuário [/user/{id}]
+ Parameters
    + id (string)

### Lista um usuário[GET]
+ Response 200 (application/json)
    + Attributes (User)
        
### Atualiza um usuário [PUT]
+ Response 200 (application/json)
    + Attributes (User)

### Deleta um usuário [DELETE]
+ Response 200 (application/json)





# Group Admin

## Evento [/evento]

### Lista todos os eventos [GET]
+ Response 200 (application/json)
    + Attributes (array[Evento])

### Lista um evento [GET /{id}]
+ Parameters
    + id (string)

+ Response 200 (application/json)

### Atualiza um evento [PUT /{id}]
+ Parameters
    + id (string)

+ Response 200 (application/json)

# Group Produtor
## Produtor [/produtor]

# Group Aplicativo
## Aplicativo [/aplicativo]